name: test_firebase_chat_app2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.3
  email_validator: ^2.1.17
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  go_router: ^9.0.3
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  date_format: ^2.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
