// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe1w41ep4llLtP8_2OkQzFixwpdmYWNiA',
    appId: '1:408782642836:web:9f55b730008c47ab111e81',
    messagingSenderId: '408782642836',
    projectId: 'chat-with-the-void-13pi',
    authDomain: 'chat-with-the-void-13pi.firebaseapp.com',
    storageBucket: 'chat-with-the-void-13pi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvF3SV2fAzVororNcYg-b5M4JkaLhyVpY',
    appId: '1:408782642836:android:b7bc854e7a8ac0ba111e81',
    messagingSenderId: '408782642836',
    projectId: 'chat-with-the-void-13pi',
    storageBucket: 'chat-with-the-void-13pi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6i3yMF6zZS-4QecqUDu3yOSVK0ehjRdk',
    appId: '1:408782642836:ios:6eea262e971b45d2111e81',
    messagingSenderId: '408782642836',
    projectId: 'chat-with-the-void-13pi',
    storageBucket: 'chat-with-the-void-13pi.appspot.com',
    iosClientId: '408782642836-q2r7nvl866ff7jcn4a93d3ff20tlochb.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFirebaseChatApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6i3yMF6zZS-4QecqUDu3yOSVK0ehjRdk',
    appId: '1:408782642836:ios:4a3d17969dd4ef87111e81',
    messagingSenderId: '408782642836',
    projectId: 'chat-with-the-void-13pi',
    storageBucket: 'chat-with-the-void-13pi.appspot.com',
    iosClientId: '408782642836-rugn1qe3bansuskjn27hb5e1rm4hcli5.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFirebaseChatApp2.RunnerTests',
  );
}
